#!/usr/bin/env bash

requirements_solaris_lib_installed()
{
  pkg info "$1" >/dev/null 2>&1 || return $?
}

requirements_solaris_ensure_libs()
{
  typeset -a packages_installed packages_missing packages_to_install
  __rvm_filter_installed_packages solaris "$@" || return $?
}

requirements_solaris_libs_install()
{
  __rvm_try_sudo pkg install "$@" ||
  {
    typeset ret=$?
    case $ret in
      (4) return 0 ;; # means nothing to install
    esac
    return $ret
  }
}

requirements_solaris_run()
{
  case "$1" in
    (update-system)
      true
      ;;
    (rvm)
      requirements_solaris_ensure_libs bash curl git text/gnu-patch
      ;;
    (jruby*head)
      requirements_solaris_ensure_libs jdk apache-ant git
      ;;
    (jruby*)
      requirements_solaris_ensure_libs jdk
      ;;
    (ir*)
      requirements_solaris_ensure_libs mono
      ;;
    (opal)
      requirements_solaris_ensure_libs node-devel
      ;;
    (*-head)
      requirements_solaris_ensure_libs text/gnu-patch developer/gcc-45 developer/library/lint system/header system/library/math/header-math file/gnu-coreutils git
      ;;
    (*)
      requirements_solaris_ensure_libs text/gnu-patch developer/gcc-45 developer/library/lint system/header system/library/math/header-math file/gnu-coreutils
      ;;
  esac
}
